### ISSUE TITLE
Update catalog views

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/prototype#69]
## Description

Our product ontology is getting a nice v2 so it's a good time to update our prototype UI to better fit demonstration needs. This issue focuses on stock update use case only. In a second iteration we will add fields needed for logistics prototypes.

## Tasks and acceptance criteria

**Catalog**

- [x] Remove sku, description and total theoritical columns

- [ ] Add quantity, unit type, name, stock and type

See mockups for order

**Product edit page**

- [ ] Remove mentions of catalog items and supply product

- [ ] Remove IDs (unless we do use them for dev purpose sometimes)

- [ ]  Add type, description, producer name, label, expiry date, stock and URL

See mockups for order

**Vocabulary**

- [x] `Import `turns into `Data`. The idea is that in this menu you can also empty the catalog. The other option would be to keep import but migrate "delete all products" on the catalog page

- [x] `Reconciliation` is not well understood (although it is technically correct). I'm proposing `Product links` or simply `links`

- [ ] Same comment for `Reconciled product` which should become simply `product`

**Clean up**

- [x]  Migrate "test OIDC" to a less visible place

## Mockups

https://design.penpot.app/#/view/10edfbd0-87e3-11eb-9126-57893f4da933?page-id=10edfbd1-87e3-11eb-9126-57893f4da933&index=0&share-id=c3fe52d0-8056-11ec-9027-96385a0e391f

**Comment by RachL** [comment]
Superseeded by https://github.com/datafoodconsortium/prototype/issues/113 and https://github.com/datafoodconsortium/prototype/issues/114
